In [15]:
import numpy as np


arr = np.array([10, 20, 30, 40, 50])
print("Original Array:", arr)


add_arr = arr + 2
print("a) After adding 2:", add_arr)


mul_arr = arr * 3
print("b) After multiplying by 3:", mul_arr)


div_arr = arr / 2
print("c) After dividing by 2:", div_arr)


Original Array: [10 20 30 40 50]
a) After adding 2: [12 22 32 42 52]
b) After multiplying by 3: [ 30  60  90 120 150]
c) After dividing by 2: [ 5. 10. 15. 20. 25.]


In [16]:
import numpy as np


arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("a) Reversed array:", reversed_arr)



def find_most_frequent(arr_input):

    counts = np.bincount(arr_input)
    most_frequent_val = np.argmax(counts)
    indices = np.where(arr_input == most_frequent_val)[0]
    return most_frequent_val, indices



x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
val_x, idx_x = find_most_frequent(x)
print(f"b) i. For array x: Most frequent value is {val_x} at indices {idx_x}")


y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

counts_y = np.bincount(y)
max_count = np.max(counts_y)
modes = np.where(counts_y == max_count)[0]

for mode in modes:
    idx_y = np.where(y == mode)[0]
    print(
        f"b) ii. For array y: Most frequent value is {mode} at indices {idx_y}"
    )


a) Reversed array: [5 4 6 3 2 1]
b) i. For array x: Most frequent value is 1 at indices [0 5 7 8 9]
b) ii. For array y: Most frequent value is 1 at indices [0 1 2]
b) ii. For array y: Most frequent value is 3 at indices [4 8 9]


In [17]:
import numpy as np


arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])



elem_a = arr[0, 1]
print("a) Element at 1st row, 2nd column:", elem_a)


elem_b = arr[2, 0]
print("b) Element at 3rd row, 1st column:", elem_b)


a) Element at 1st row, 2nd column: 20
b) Element at 3rd row, 1st column: 70


In [18]:
import numpy as np


your_name = np.linspace(10, 100, 25)
print("Array details:")
print("Dimensions (ndim):", your_name.ndim)
print("Shape:", your_name.shape)
print("Total elements (size):", your_name.size)
print("Data type (dtype):", your_name.dtype)
print("Total bytes consumed:", your_name.nbytes)



reshaped_transpose = your_name.reshape(-1, 1)
print("\nTranspose using reshape(-1, 1):\n", reshaped_transpose)


print("\nCan we use .T on 1D directly?")
print(
    "No, using your_name.T on a true 1D array returns the exact same 1D array: ",
    your_name.T.shape,
)
print(
    "To make .T work like a matrix transpose, we must first add an axis, e.g., your_name[np.newaxis, :].T"
)


Array details:
Dimensions (ndim): 1
Shape: (25,)
Total elements (size): 25
Data type (dtype): float64
Total bytes consumed: 200

Transpose using reshape(-1, 1):
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Can we use .T on 1D directly?
No, using your_name.T on a true 1D array returns the exact same 1D array:  (25,)
To make .T work like a matrix transpose, we must first add an axis, e.g., your_name[np.newaxis, :].T


In [19]:
import numpy as np


ucs420_parth = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("Original 3x4 Array:\n", ucs420_parth)


print("\n--- Statistics ---")
print("Mean:", np.mean(ucs420_parth))
print("Median:", np.median(ucs420_parth))
print("Max:", np.max(ucs420_parth))
print("Min:", np.min(ucs420_parth))
print("Unique elements:", np.unique(ucs420_parth))


reshaped_ucs420_parth = ucs420_your_name.reshape(4, 3)
print("\n--- Reshaped Array (4x3) ---\n", reshaped_ucs420_parth)



resized_ucs420_parth = np.resize(ucs420_your_name, (2, 3))
print("\n--- Resized Array (2x3) ---\n", resized_ucs420_parth)


Original 3x4 Array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

--- Statistics ---
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

--- Reshaped Array (4x3) ---
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

--- Resized Array (2x3) ---
 [[10 20 30]
 [40 50 60]]
