In [1]:
import numpy as np


temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])


corrected_temp = temperature + 2
print("a. Corrected temperatures (+2°C):", corrected_temp)


fahrenheit_temp = (9 / 5) * corrected_temp + 32
print("b. Temperatures in Fahrenheit:", fahrenheit_temp)



greater_than_32 = corrected_temp[corrected_temp > 32]
print("c. Readings greater than 32°C:", greater_than_32)


count_exceed_32 = np.sum(corrected_temp > 32)
print("d. Number of readings exceeding 32°C:", count_exceed_32)


"""
e. Explanation:
Explicitly iterating through an array using a 'for' loop in Python introduces
significant overhead because Python is an interpreted language. The loop executes
at the Python layer, checking types and handling objects dynamically at each step.

Vectorization and Boolean indexing offload these computations to highly optimized,
compiled C code under the hood of NumPy. This allows operations to run at near-hardware
speeds using SIMD (Single Instruction, Multiple Data) processor instructions.
Additionally, NumPy processes continuous memory blocks, maximizing CPU cache utilization
and drastically speeding up data processing.
"""


a. Corrected temperatures (+2°C): [27 30 33 37 40 29 35 42]
b. Temperatures in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
c. Readings greater than 32°C: [33 37 40 35 42]
d. Number of readings exceeding 32°C: 5


"\ne. Explanation:\nExplicitly iterating through an array using a 'for' loop in Python introduces\nsignificant overhead because Python is an interpreted language. The loop executes\nat the Python layer, checking types and handling objects dynamically at each step.\n\nVectorization and Boolean indexing offload these computations to highly optimized,\ncompiled C code under the hood of NumPy. This allows operations to run at near-hardware\nspeeds using SIMD (Single Instruction, Multiple Data) processor instructions.\nAdditionally, NumPy processes continuous memory blocks, maximizing CPU cache utilization\nand drastically speeding up data processing.\n"

In [2]:
import numpy as np


steps = np.array([
    [7000, 7500, 8000],
    [10000, 11000, 10500],
    [5000, 5500, 6000],
    [9000, 8500, 9500]
])


total_steps = np.sum(steps)
print("a. Total steps recorded:", total_steps)


mean_steps = np.mean(steps)
print("b. Mean number of steps:", mean_steps)


max_steps = np.max(steps)
min_steps = np.min(steps)
print(f"c. Maximum steps: {max_steps}, Minimum steps: {min_steps}")


daily_total_steps = np.sum(steps, axis=0)
print("d. Total steps for each day (Day 1, 2, 3):", daily_total_steps)


user_total_steps = np.sum(steps, axis=1)
print("e. Total steps for each user (User 1, 2, 3, 4):", user_total_steps)


flat_max_idx = np.argmax(steps)

user_idx, day_idx = np.unravel_index(flat_max_idx, steps.shape)
print(f"f. Maximum steps position: Row {user_idx} (User {user_idx+1}), Column {day_idx} (Day {day_idx+1})")

a. Total steps recorded: 97500
b. Mean number of steps: 8125.0
c. Maximum steps: 11000, Minimum steps: 5000
d. Total steps for each day (Day 1, 2, 3): [31000 32500 34000]
e. Total steps for each user (User 1, 2, 3, 4): [22500 31500 16500 27000]
f. Maximum steps position: Row 1 (User 2), Column 1 (Day 2)


In [3]:
import numpy as np


original = np.array([1, 2, 3, 4, 5, 6])
print("a. Original array:", original)


subset = original[1:4]
print("b. Subset slice:", subset)


subset[0] = 999
print("c. After modifying subset:")
print("   Subset:", subset)
print("   Original (affected because slicing creates a view):", original)


original = np.array([1, 2, 3, 4, 5, 6])


copied_array = original[1:4].copy()
copied_array[0] = 500
print("d. After modifying explicit copy:")
print("   Copied array:", copied_array)
print("   Original (unaffected because copy creates a new allocation):", original)


matrix_3x4 = np.arange(1, 13).reshape(3, 4)
print("\ne. Reshaped 3x4 Matrix:\n", matrix_3x4)


print("\nf. Extractions:")
print("   First row:", matrix_3x4[0, :])
print("   Last row:", matrix_3x4[-1, :])
print("   Second column:", matrix_3x4[:, 1])

print("   Elements from rows 1-2 and columns 2-3:\n", matrix_3x4[1:3, 2:4])


flattened = matrix_3x4.flatten()
raveled = matrix_3x4.ravel()
print(f"\ng. Flattened: {flattened}")
print(f"   Raveled: {raveled}")


raveled[0] = 99
print("\nh. Modifying ravel()[0] to 99...")
print("   Original 3x4 Matrix (affected because ravel returns a view whenever possible):\n", matrix_3x4)


flattened[1] = 88
print("\ni. Modifying flatten()[1] to 88...")
print("   Original 3x4 Matrix (unaffected because flatten always returns a deep copy):\n", matrix_3x4)


print("\nj. Matrix Properties:")
print("   Shape:", matrix_3x4.shape)
print("   Number of dimensions (ndim):", matrix_3x4.ndim)
print("   Total size:", matrix_3x4.size)
print("   Data type (dtype):", matrix_3x4.dtype)


a. Original array: [1 2 3 4 5 6]
b. Subset slice: [2 3 4]
c. After modifying subset:
   Subset: [999   3   4]
   Original (affected because slicing creates a view): [  1 999   3   4   5   6]
d. After modifying explicit copy:
   Copied array: [500   3   4]
   Original (unaffected because copy creates a new allocation): [1 2 3 4 5 6]

e. Reshaped 3x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

f. Extractions:
   First row: [1 2 3 4]
   Last row: [ 9 10 11 12]
   Second column: [ 2  6 10]
   Elements from rows 1-2 and columns 2-3:
 [[ 7  8]
 [11 12]]

g. Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]
   Raveled: [ 1  2  3  4  5  6  7  8  9 10 11 12]

h. Modifying ravel()[0] to 99...
   Original 3x4 Matrix (affected because ravel returns a view whenever possible):
 [[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

i. Modifying flatten()[1] to 88...
   Original 3x4 Matrix (unaffected because flatten always returns a deep copy):
 [[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

j. M

In [4]:
import numpy as np


y = np.array([40, 65, 30, 85])
X = np.array([
    [6, 50, 9],
    [7, 60, 7],
    [5, 45, 6],
    [4, 30, 8]
])


print("a. X Shape:", X.shape)
print("   X Dimensions:", X.ndim)


X_T = X.T
print("\nb. Transpose X.T:\n", X_T)
"""
Explanation: The transpose swaps the rows and columns of X.
In the context of the data, while each row of X represented a specific user's features,
each row of X.T now isolates a specific feature (Row 0 = Sleep hours, Row 1 = Activity level,
Row 2 = Stress level) across all users.
"""


XTX = X_T @ X
print("\nc. Matrix Product (X.T @ X):\n", XTX)


XTX_inv = np.linalg.inv(XTX)
print("\nd. Inverse Matrix (X.T @ X)^-1:\n", XTX_inv)


beta = XTX_inv @ X_T @ y
print("\ne. Calculated OLS Coefficients (beta):", beta)


"""
f. Coefficient Explanation:
The array contains 3 values [beta_0, beta_1, beta_2] mapping directly to the features:
1. beta_0 (Sleep hours): Weight impact of sleep duration on the assistance score.
2. beta_1 (Activity level): Weight impact of daily physical activity on the score.
3. beta_2 (Stress level): Weight impact of psychological stress on the score.

Each coefficient details how much the predicted assistance score changes when that
specific feature increases by 1 unit, keeping all other features constant.
"""


new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta
print(f"\ng. Predicted assistance score for new user {new_user}: {predicted_score:.2f}")

a. X Shape: (4, 3)
   X Dimensions: 2

b. Transpose X.T:
 [[ 6  7  5  4]
 [50 60 45 30]
 [ 9  7  6  8]]

c. Matrix Product (X.T @ X):
 [[ 126 1065  165]
 [1065 9025 1380]
 [ 165 1380  230]]

d. Inverse Matrix (X.T @ X)^-1:
 [[12.4845173  -1.2568306  -1.41530055]
 [-1.2568306   0.12786885  0.13442623]
 [-1.41530055  0.13442623  0.21311475]]

e. Calculated OLS Coefficients (beta): [106.58469945 -11.06557377  -2.78688525]

g. Predicted assistance score for new user [ 5 40  7]: 70.79
